### ISSUE TITLE
Add support for fingerprint images taken using camera

### ISSUE THREAD

**Issue by vishalsaugat** [Utkarsh-Deshmukh/Fingerprint-Enhancement-Python#8] opened 2020-09-29 09:07 UTC
Hey Utkarsh, it would be helpful if we will be able to enhance fingerprints taken by camera. Attaching a sample image
![IMG_5324 small](https://user-images.githubusercontent.com/5698626/94538291-78668500-0261-11eb-83d3-65716a4fac8a.jpg)

**Comment by Utkarsh-Deshmukh** [comment] 2020-09-29 16:40
Hey Vishal.
Originally this algorithm was not intended to enhance images taken from the camera. It was intended to be used for images taken from fingerprint scanner. The images from the camera are fundamentally very different from the images taken from the fingerprint scanner.
Here are some of the issues in the images taken from camera:
1) Field of view - this can change from image to image since it is dependent on the person capturing the image, and the camera with which the image is being captured.
2) Geometric distortion - the image can have in plane rotation, scale, shear, tilt and perspective.
3) Focus failures - Since the image is taken from a cellphone camera, there may be instances where there are focus failures (camera fails to focus on the subject)
4) uneven contrast in images - This is seen in the example image above. Some parts of the image are very bright whereas some parts of the image are darker. This can truly mess up the enhancement algorithm.

Knowing all these limitations, I still believe that there is potential of using this enhancement algorithm by tweaking some blocks in it and making it work for the above image.

The biggest issue that I see here is that the contrast is uneven. We can sort this by doing a histogram equalization.
If we do that, we need not perform the "normalize" function in ridge_segment.py

I have created a branch labelled "**WorkingForCameraImages**" It works decently on the image that you have provided. Please check it out and let me know if the result looks satisfactory.

Thanks and Regards

**Comment by Utkarsh-Deshmukh** [comment] 2020-09-29 16:43
if you want to improve the quality even more, I recommend performing local contrast normalization on the input image and then sending it into the algorithm. 

Another thing which you might want to tweak is ROI estimation in the ridge_segment script. The ROI mask is generated by computing a local standard deviation on the image. The size of the locality for this is dictated by the variable "blksze", experimenting with this value might be useful

**Comment by vishalsaugat** [comment] 2020-09-29 20:24
Hey Utkarsh, I have tested the algorithm without tweaking parameters and it's working pretty good. 
As you rightly pointed , the biggest issue here is uneven contrast and that the focus is mainly on the middle part of finger. As we go towards the edge , fingerprints become lesser and lesser visible. 
Can we take multiple images and map some common features to compile a clear image ? I know it sounds kinda difficult

Another small issue is that sometime background also contains lines . Attaching the image for it
![check_3_3](https://user-images.githubusercontent.com/5698626/94611785-e04bb880-02bf-11eb-9c50-0371ea730275.jpg)
. Can we solve it with finger boundary detection and detect lines only in the area enclosed within finger boundary. 

Overall the current solution also looks good, thanks a lot 👍

**Comment by Utkarsh-Deshmukh** [comment] 2020-09-29 20:37
@vishalsaugat if you run the version which is in the branch "**WorkingForCameraImages**", I get this output:
![check_3](https://user-images.githubusercontent.com/13918778/94613035-d17deb00-0258-11eb-9e56-dc9129654c5e.jpg)

This looks much cleaner than your output. So I feel having a histogram equalization block is a valid strategy choice.

**Comment by Utkarsh-Deshmukh** [comment] 2020-09-29 20:39
you can provide a manual region of interest selector which will help the user to restrict the finger in the image into a certain location. that would help you avoid false edges coming from background content.

**Comment by vishalsaugat** [comment] 2020-09-29 20:44
@Utkarsh-Deshmukh I have tested using your branch **WorkingForCameraImages** only. But I guess the output is not clear because the fingerprint is not of that good quality , so that can be improved by taking a better image.

**Comment by vishalsaugat** [comment] 2020-09-29 20:45
Yeah that's a good idea to keep a manual region  for finger placement.

**Comment by Utkarsh-Deshmukh** [comment] 2020-09-29 20:51
you can probably have crosshairs or a bounding box to restrict the user to place the finger anywhere else. The field of view is going to be a challenge.. The closer you are to the camera, the narrower the fov. so the central part will be in focus and the parts away from the center will start getting blur. there is not much we can do in that case, since the blur causes loss in high frequency of the image content.

**Comment by vishalsaugat** [comment] 2020-09-29 20:53
Also, I am not getting a good result for thumb. I started tweaking **blksize**, but the result is pretty much same. Any suggestion on what else I can tweak ?[
![check_3](https://user-images.githubusercontent.com/5698626/94614507-e6dc2f00-02c3-11eb-9e4d-03f46db6a863.jpg)
![3](https://user-images.githubusercontent.com/5698626/94614526-ee9bd380-02c3-11eb-96e6-08d47a4153a8.jpg)

](url)

**Comment by Utkarsh-Deshmukh** [comment] 2020-09-29 20:59
I would recommend experimenting with local contrast adjustment. Basically divide the image into small chunks, and fix the contrast variation. I think just by doing that, you might see a substantial improvement.

**Comment by vishalsaugat** [comment] 2020-09-30 21:13
Keeping the finger at a distance worked to reduce the contrast variation.
Closing the issue now. Thanks again for the help Utkarsh.

**Comment by Utkarsh-Deshmukh** [comment] 2020-09-30 21:22
if possible, can you share the input and the output?

**Comment by AliAbbasAli** [comment] 2023-09-07 10:03
> if possible, can you share the input and the output?

Hey utkarsh I am working on same fingerprint extraction can u help me with the source code 
I checked ur code of workingforcameraimages 
But I want to extract from finger image ..
Pls it will be really helpful

**Comment by Utkarsh-Deshmukh** [comment] 2023-09-07 16:27
@AliAbbasAli can you send a sample image on which you are trying to run the enhancement algorithm?

**Closed as completed** 2023-12-29 00:35 UTC

**Comment by Devsharma-ai** [comment] 2024-01-03 10:42
> @vishalsaugat if you run the version which is in the branch "**WorkingForCameraImages**", I get this output: ![check_3](https://user-images.githubusercontent.com/13918778/94613035-d17deb00-0258-11eb-9e56-dc9129654c5e.jpg)
> 
> This looks much cleaner than your output. So I feel having a histogram equalization block is a valid strategy choice.

hlo buddy can you provide me source code for this , i mean like this output for the camera image ??  this is  pretty much clear for the camera image ??/ soo plz if you then plz provide me ?

**Comment by Utkarsh-Deshmukh** [comment] 2024-01-03 18:25
@Devsharma-ai please check out the branch `WorkingForCameraImages` to get this.. **NOTE: this branch is not maintained, and may be behind the develop. you can refer to the changes in this branch to get this working for your use case**

Summary of the changes:
1) adding histogram equalization while performing ridge_segmentation
2) changing binarization to generate the binary output after performing `ridge filter `.

**Comment by Utkarsh-Deshmukh** [comment] 2024-01-03 18:27
@Devsharma-ai 
I will work on this and make this available in the next release. Will need some time for it though.. meanwhile you can use the branch `WorkingForCameraImages`

**Comment by Devsharma-ai** [comment] 2024-01-03 18:40
Thanx for reverting back , can you provide me your any social contact
because i need some help on fingerprint analysis for my little assesment??
Can you?
And my first step is taking camera image and enhanced like that it's a high
quality scanner print soo i m confused little bit how to start? And many
step after that and a big challenge for me to count ridges count from core
to delta in fingerprint?? Any source code or any resources if you want to
provide me, if yes  plz let me know thankyou ☺️

**Comment by Utkarsh-Deshmukh** [comment] 2024-01-03 18:59
@Devsharma-ai you can find my email on my github profile. send me a message there and we can coordinate.. also send me some sample images that you are working on, so that I can run it on my end.

**Comment by Devsharma-ai** [comment] 2024-01-04 02:51
Thanks, I will.

**Comment by Devsharma-ai** [comment] 2024-01-04 11:12
Can you help me if i want to count a ridges from core to delta in diffrent
patterns of finger? I mean how to do that ?? Or how recognize a pattern.??
After enhancement?

**Comment by Utkarsh-Deshmukh** [comment] 2024-01-04 17:11
I am not sure that I understand your request. is there some example that you can provide? images and pictures would help.

Since this topic is not regarding fingerprint-image-enhancement, it would be good to take it offline. please send me a personal email and we can discuss it there.
Best Regards

**Comment by Devsharma-ai** [comment] 2024-01-05 06:01
I'm working on this type of image which I attach , and my requirement is to
count the ridges from core to delta in the fingerprint.for each pattern
like loop ,whorl . if you have any idea about core and delta counting then
suggest me resource ty ..

**Comment by Utkarsh-Deshmukh** [comment] 2024-01-05 18:58
i have a couple of thoughts about this:
1) when you run the fingerprint-image-enhancement, you will get the binary enhanced image. then you first need to find the location of the delta. this can be done using one of the following methods:
 i) Pattern matching
 ii) triangle fitting on three points
 iii) finding 3-ridge-bifurcation points which are in a triangular shape
 (please take a look at [this repo](https://github.com/Utkarsh-Deshmukh/Fingerprint-Feature-Extraction) to understand how  we find ridge-bifurcations and ridge-terminations)
 
2) once you have the location of the core and the delta, you can throw a scan line between these points, and count the number of ridges by performing simple zero crossing detector on the edges.

3) I would strongly recommend going over [this repo](https://github.com/Utkarsh-Deshmukh/Fingerprint-Feature-Extraction) to understand how minutiae features are extracted from the enhanced fingerprint images.

**Comment by skyestudiosDev** [comment] 2024-12-03 12:00
Did you later support this? Or the `WorkingForCameraImages ` is still the way to go?

**Comment by APeFerreira** [comment] 2025-10-14 12:22
> Did you later support this? Or the `WorkingForCameraImages ` is still the way to go?

I'd also like to know

**Comment by Utkarsh-Deshmukh** [comment] 2025-10-26 20:05
Currently there is no plan to officially release this for camera images.
For the time being using the branch `WorkingForCameraImages` is still the best alternative
