### ISSUE TITLE
Error occurring in ridge_filter

### ISSUE THREAD

**Issue by AarthiA30** [Utkarsh-Deshmukh/Fingerprint-Enhancement-Python#9] opened 2021-01-13 15:21 UTC
![Capture](https://user-images.githubusercontent.com/77399870/104471525-f9fbdc00-55e0-11eb-9f24-40f8d80e3b90.JPG)

**Comment by Utkarsh-Deshmukh** [comment] 2021-01-13 16:14
Can you share the image so that I can recreate the error on my end?

**Comment by AarthiA30** [comment] 2021-01-13 16:24
I am preprocessing a folder full of png images. Could you help me in
preprocessing the images which could help me in doing my project.

>

**Comment by Utkarsh-Deshmukh** [comment] 2021-01-13 16:47
It seems like the image f0001&01.png caused this error. Send this image so that I can take a look at what is wrong

**Comment by Utkarsh-Deshmukh** [comment] 2021-01-14 20:58
@AarthiA30 can you please share the image that was causing this issue. That will help me create the issue on my end.

**Comment by m3di** [comment] 2021-01-18 07:51
@Utkarsh-Deshmukh hi. i have faced the same error:

`IndexError: index 0 is out of bounds for axis 0 with size 0`

the exact line which cusses this error is in `__ridge_filter` function: 

`sigmax = 1 / unfreq[0] * self.kx`

and this is my input image:

`https://drive.google.com/u/0/uc?id=1VnGEvgZj7AxeBLayqs8BAIQPFtWJLJz7&export=download`

the image shape is `(132, 100)`

thanks

**Comment by Utkarsh-Deshmukh** [comment] 2021-01-19 03:01
@m3di thank you for providing the image.
The issue with this image is that it is quite small (much smaller than what the algorithm was intended for)

There are two ways to fix the issue for your image:
1) you can call the enhancement function with the "resize" parameter to be "True":
 ``` out = fingerprint_enhancer.enhance_Fingerprint(img, resize=True) ```
 
2) you can call the enhancement function by providing the "min_wave_length" parameter to be small. I tried and it worked with a value of 4:
``` out = fingerprint_enhancer.enhance_Fingerprint(img, min_wave_length = 4) ```

Hope this helps.

**Comment by Utkarsh-Deshmukh** [comment] 2021-01-20 21:53
@AarthiA30 , @m3di did this fix the issue for you guys? should I go ahead and close this issue?

**Comment by m3di** [comment] 2021-01-20 22:00
@Utkarsh-Deshmukh yes, i used the resize option and it solved the issue, thank you so much. in fact i was so excited about the next steps on my project, i did forget to write it here 😅

**Closed** 2021-01-20 22:02 UTC
