### ISSUE TITLE
Gabor_Filter Float Error

### ISSUE THREAD

**Issue by sunshineS123** [Utkarsh-Deshmukh/Fingerprint-Enhancement-Python#2] opened 2018-06-05 11:50 UTC
Hi Utkarsh,
When I run your code,
I get the following error

> Macintosh:src saikiranoruganti$ python main_enhancement.py
------
 >     gabor_filter = np.array(np.zeros((180/angleInc,filt_rows,filt_cols)));
> TypeError: 'float' object cannot be interpreted as an integer
> Macintosh:src saikiranoruganti$ 180/angleInc,filt_rows,filt_cols
> 
**It seems the floats are unable to pass through np.zeros. Any directions on how to fix this?**

**Comment by Utkarsh-Deshmukh** [comment] 2018-06-08 16:58
could you send me the image that you are working with. Let me try to recreate your error on my end.

**Comment by Utkarsh-Deshmukh** [comment] 2018-06-08 17:06
on that line, we are create a 3D array which would store the gabor filters. Every dimension consists of a 2D matrix of size (filt_rowsxfilt_cols); all the three inputs (180/angleInc, filt_rows, filt_cols) must be integers.
The easiest hack for your problem, would be to round them or convert them to integers.

**Comment by sunshineS123** [comment] 2018-06-08 17:48
Thanks for the reply Utkarsh,
I am attaching the images i have used 
![3](https://user-images.githubusercontent.com/37661151/41172530-18564fda-6b8f-11e8-999a-7b2d222ff7f4.jpg)
![4](https://user-images.githubusercontent.com/37661151/41172537-1d46e036-6b8f-11e8-8015-51754d387c90.jpg)
managed to get some result using PyCharm Edu after few bug fixes and installations, but i still get the same error in python3 and docker.
This is the result image but its not accurate as yours, can you suggest.
![3](https://user-images.githubusercontent.com/37661151/41172640-6a7bf030-6b8f-11e8-95fa-00f0c57c7f75.jpg)
![4](https://user-images.githubusercontent.com/37661151/41172650-71c176a8-6b8f-11e8-805c-161c9a0f1456.jpg)

Thanks

**Comment by sunshineS123** [comment] 2018-06-19 07:51
ok, Thanks

**Comment by Kkaranmore** [comment] 2019-03-09 20:27
hey I converted it to integer then it shown this error

cscale = cmax - cmin
TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.

**Comment by Kkaranmore** [comment] 2019-03-09 20:27
please help

**Comment by Utkarsh-Deshmukh** [comment] 2019-03-11 22:04
Could you send me a snapshot of the error?

**Comment by wahyubram82** [comment] 2019-04-06 13:38
i have the same problem...
gabor_filter = np.array(np.zeros((180/angleInc, int(filt_rows), int(filt_cols))))
TypeError: 'float' object cannot be interpreted as an integer

i try to understood the problem. 
so i make a debug process to know every type component to process. i load it here to inform many people who use your script.
this is the process before it error (at section: 'ridge_filter(normim, orientim, freq, kx, ky)' function)

the function that error:
newim = ridge_filter(normim, orientim, freq, kx, ky)

the value type that running by that function:
normim: numpy.ndarray
orientim: numpy.ndarray
freq: numpy.ndarray
kx: float
ky: float

then i monitoring the process in the function of 'ridge_filter' and watch the value type change.

#ridge_filter(normim, orientim, freq, kx, ky)#
angleInc = 3       ->(int)
im = np.double(im)     -> np.double(im) = np.double(normim) -> type(im) = numpy.ndarray
rows,cols = im.shape    -> rows = int ; colls = int
newim = np.zeros((rows,cols)) ->newim = numpy.ndarray
freq_1d = np.reshape(freq,(1,rows*cols)) -> numpy.ndarray
ind = np.where(freq_1d>0) ->ind = tuple
ind = np.array(ind) -> ind = numpy.ndarray
ind = ind[1,:] ->  ind = numpy.ndarray
non_zero_elems_in_freq = freq_1d[0][ind] -> numpy.ndarray
non_zero_elems_in_freq = np.double(np.round((non_zero_elems_in_freq*100)))/100 ->  numpy.ndarray
unfreq = np.unique(non_zero_elems_in_freq) -> numpy.ndarray

sigmax = 1/unfreq[0]*kx   -> numpy.float64
sigmay = 1/unfreq[0]*ky -> numpy.float64
sze = np.round(3*np.max([sigmax,sigmay])) -> numpy.float64

x,y = np.meshgrid(np.linspace(-sze,sze,(2*sze + 1)),np.linspace(-sze,sze,(2*sze + 1)))   -> x and y -> numpy.ndarray

reffilter = np.exp(-(( (np.power(x,2))/(sigmax*sigmax) + (np.power(y,2))/(sigmay*sigmay)))) * np.cos(2*np.pi*unfreq[0]*x)        -> refilter type = numpy.ndarray

filt_rows, filt_cols = reffilter.shape -> filt_rows and filt_cols  is --integer-- type.

***EVERYTHING NORMAL, UNTIL THIS POSITION***

THEN:
gabor_filter = np.array(np.zeros((180/angleInc), (filt_rows), (filt_cols))) -> error. 
error type:  'float' object cannot be interpreted as an integer

the simple variable from gabor_filter = np.array(np.zeros((180/angleInc), (filt_rows), (filt_cols)))
```
cek = np.zeros(a,b,c)
res = np.array(cek)
which:
a - > (180/angleInc) -> float
b -> filt_rows -> int
c -> filt_cols -> int
```

gotcha.....

at here, we found the problem come from here which is:
`np.zeros((180/angleInc), (filt_rows), (filt_cols))`
the form of np.zeros is:
np.zeros(shape, dtype=datatype)

i try to cek the resolve with testing like this:
```
shape = (int(180/angleInc), (filt_rows), (filt_cols))
zeros = np.zeros(shape, dtype = int)
gabor_filter = np.array(zeros)
```

work like charming...

so the conclution of correction should be modified the 'ridge_filter.py' file, at line 88, become

`gabor_filter = np.array(np.zeros((int(180/angleInc), (filt_rows), (filt_cols)), dtype = int))`

i try to fix that line in the file 'ridge_filter.py', please confirm it.

**Comment by Utkarsh-Deshmukh** [comment] 2019-04-09 21:16
> hey I converted it to integer then it shown this error
> 
> cscale = cmax - cmin
> TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.

The imsave function in scipy.misc is outdated.
try **scipy.misc.imsave('../enhanced/' + img_name, 255*(enhanced_img))** in the main_enhancement.py file

**Comment by Utkarsh-Deshmukh** [comment] 2019-04-09 21:31
> i have the same problem...
> gabor_filter = np.array(np.zeros((180/angleInc, int(filt_rows), int(filt_cols))))
> TypeError: 'float' object cannot be interpreted as an integer
> 
> i try to understood the problem.
> so i make a debug process to know every type component to process. i load it here to inform many people who use your script.
> this is the process before it error (at section: 'ridge_filter(normim, orientim, freq, kx, ky)' function)
> 
> the function that error:
> `newim = ridge_filter(normim, orientim, freq, kx, ky)`
> 
> the value type that running by that function:
> 
> ```
> normim: numpy.ndarray
> orientim: numpy.ndarray
> freq: numpy.ndarray
> kx: float
> ky: float
> ```
> then i monitoring the process in the function of 'ridge_filter' and watch the value type change.
> 
> ```
> #ridge_filter(normim, orientim, freq, kx, ky)#
> angleInc = 3       ->(int)
> im = np.double(im)     -> np.double(im) = np.double(normim) -> type(im) = numpy.ndarray
> rows,cols = im.shape    -> rows = int ; colls = int
> newim = np.zeros((rows,cols)) ->newim = numpy.ndarray
> freq_1d = np.reshape(freq,(1,rows*cols)) -> numpy.ndarray
> ind = np.where(freq_1d>0) ->ind = tuple
> ind = np.array(ind) -> ind = numpy.ndarray
> ind = ind[1,:] ->  ind = numpy.ndarray
> non_zero_elems_in_freq = freq_1d[0][ind] -> numpy.ndarray
> non_zero_elems_in_freq = np.double(np.round((non_zero_elems_in_freq*100)))/100 ->  numpy.ndarray
> unfreq = np.unique(non_zero_elems_in_freq) -> numpy.ndarray
> 
> sigmax = 1/unfreq[0]*kx   -> numpy.float64
> sigmay = 1/unfreq[0]*ky -> numpy.float64
> sze = np.round(3*np.max([sigmax,sigmay])) -> numpy.float64
> 
> x,y = np.meshgrid(np.linspace(-sze,sze,(2*sze + 1)),np.linspace(-sze,sze,(2*sze + 1)))   -> x and y -> numpy.ndarray
> 
> reffilter = np.exp(-(( (np.power(x,2))/(sigmax*sigmax) + (np.power(y,2))/(sigmay*sigmay)))) * np.cos(2*np.pi*unfreq[0]*x)        -> refilter type = numpy.ndarray
> 
> filt_rows, filt_cols = reffilter.shape -> filt_rows and filt_cols  is --integer-- type.
> 
> ***EVERYTHING NORMAL, UNTIL THIS POSITION***
> 
> THEN:
> gabor_filter = np.array(np.zeros((180/angleInc), (filt_rows), (filt_cols))) -> error. 
> error type:  'float' object cannot be interpreted as an integer
> ```
> the simple variable from
> 
> ```
> gabor_filter = np.array(np.zeros((180/angleInc), (filt_rows), (filt_cols)))
> 
> is:
> gabor_filter =np.array(np.zeros(a,b,c))
> 
> it's a simplification writing type mode.
> 
> to, make a debuging it's should be reform to step by step mode / not simple mode.
> so it become:
> cek = np.zeros(a,b,c)
> res = np.array(cek)
> which:
> a - > (180/angleInc) -> float
> b -> filt_rows -> int
> c -> filt_cols -> int
> ```
> and gotcha.....
> 
> at here, we found the problem come from here which is:
> `np.zeros((180/angleInc), (filt_rows), (filt_cols))`
> the form of np.zeros is:
> `np.zeros(shape, dtype=datatype)`
> 
> i try to cek the resolve with testing like this:
> 
> ```
> shape = (int(180/angleInc), (filt_rows), (filt_cols))
> zeros = np.zeros(shape, dtype = int)
> gabor_filter = np.array(zeros)
> ```
> work like charming...
> 
> so the conclution of correction should be modified the 'ridge_filter.py' file, at line 88, become
> 
> `gabor_filter = np.array(np.zeros((int(180/angleInc), (filt_rows), (filt_cols)), dtype = int))`
> 
> i try to fix that line in the file 'ridge_filter.py', please confirm it.
> 
> EDIT:
> normally in coding, another error show up after fixing the other one.
> 
> problem is here (ridge_filter.py), again, in line:
> 
> ```
> for o in range(0,180/angleInc):`
>     rot_filt = scipy.ndimage.rotate(reffilter,-(o*angleInc + 90),reshape = False)
>     gabor_filter[o] = rot_filt
> ```
> the value of: (0,180/angleInc) is = (0, 60.0)
> 
> because, i don't understood your purpose to iter the result of (0,180/angleInc) = (0, 60.0) is to get:
> 
> number from 0 to 60
> or just to get 0 and 60
> i'm still not made any propose to change in this part.
> my recommendation to fix is:
> 
> ```
> angle_for_iter = (0,180/angleInc)
> start_angle, last_angle = angle_for_iter
> start_angle = int(start_angle)
> last_angle = int(last_angle)
> 	
> for o in range(start_angle, last_angle):
>     rot_filt = scipy.ndimage.rotate(reffilter,-(o*angleInc + 90),reshape = False)
>     gabor_filter[o] = rot_filt
> ```
> the last, what the purpose of the command in: 'image_enhance.py', at last line:
> 'return (newim < -3)'
> 
> the value of newim is:
> 
> ```
> array([[0., 0., 0., ..., 0., 0., 0.],
>        [0., 0., 0., ..., 0., 0., 0.],
>        [0., 0., 0., ..., 0., 0., 0.],
>        ...,
>        [0., 0., 0., ..., 0., 0., 0.],
>        [0., 0., 0., ..., 0., 0., 0.],
>        [0., 0., 0., ..., 0., 0., 0.]])
> ```
> if we put it with:
> `return (newim < -3)`
> become:
> 
> ```
> array([[False, False, False, ..., False, False, False],
>        [False, False, False, ..., False, False, False],
>        [False, False, False, ..., False, False, False],
>        ...,
>        [False, False, False, ..., False, False, False],
>        [False, False, False, ..., False, False, False],
>        [False, False, False, ..., False, False, False]])
> ```
> at it caused the image become totally dark.
> 
> please review it..thanks
> 
> btw, the file that i try to enchance is:
> https://www.futurity.org/wp/wp-content/uploads/2017/04/fingerprint_1600.jpg
> 
> i search a true bad example to find out is this script is working or not....

1) ridge_filter: the correct syntax should be **np.array(np.zeros((180//angleInc, filt_rows, filt_cols)))**
 your alternate implementation of **gabor_filter = np.array(np.zeros((int(180/angleInc), (filt_rows), (filt_cols)), dtype = int))** shouls be fine

2) in the for loop in ridge_filter.py, the purpose is to get all rotaions values from 0 to 60.

3) image_enhance.py: The purpose of the line **return (newim < -3)** is to binarize the output.
you could change the saving method to **scipy.misc.imsave('enhanced/' + img_name, 255*enhanced_img)**

**Comment by wahyubram82** [comment] 2019-04-16 14:21
thanks for your reponses....but it keep give me picture which it, totally black.

please try your script to this picture:
https://www.futurity.org/wp/wp-content/uploads/2017/04/fingerprint_1600.jpg

**Comment by Utkarsh-Deshmukh** [comment] 2019-04-16 18:03
> thanks for your reponses....but it keep give me picture which it, totally black.
> 
> please try your script to this picture:
> https://www.futurity.org/wp/wp-content/uploads/2017/04/fingerprint_1600.jpg

It is funny because i am getting the enhanced image out. Here is my output:
![image](https://user-images.githubusercontent.com/13918778/56233149-4b0b2480-6037-11e9-8bd6-36c1e01f88e6.png)

**Comment by Kkaranmore** [comment] 2019-04-18 06:42
> Could you send me a snapshot of the error?

![2019-04-18 (27)](https://user-images.githubusercontent.com/47469561/56341576-1f24a600-61d3-11e9-97e5-9860eb8a394e.png)
this is the error its showing me
please help

**Comment by Kkaranmore** [comment] 2019-04-18 06:56
> Could you send me a snapshot of the error?

![2019-04-18 (28)](https://user-images.githubusercontent.com/47469561/56341688-79be0200-61d3-11e9-8a1e-a3130c8732ef.png)

this is the error its showing me after i round the values into integers

![2019-04-18 (29)](https://user-images.githubusercontent.com/47469561/56342251-1cc34b80-61d5-11e9-81c5-a4a63588dcf1.png)

**Comment by Utkarsh-Deshmukh** [comment] 2019-04-19 23:18
Sorry for the late reply. I was able to replicate the error you are seeing "{TypeError}numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead."

This is coming from the scipy.misc.imsave function.

The enhanced_img is a boolean image and scipy.misc.imsave cannot directly save boolean matrices.
One easy hack around this is you save the image after multiplying it by 255. This will convert its datatype from bool to int32. Now the scipy.mics.imsave can save the image properly.

Just try changing the line scipy.misc.imsave('../enhanced/' + img_name,enhanced_img); to scipy.misc.imsave('../enhanced/' + img_name, 255*enhanced_img);

**Comment by Kkaranmore** [comment] 2019-04-22 05:28
> Sorry for the late reply. I was able to replicate the error you are seeing "{TypeError}numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead."
> 
> This is coming from the scipy.misc.imsave function.
> 
> The enhanced_img is a boolean image and scipy.misc.imsave cannot directly save boolean matrices.
> One easy hack around this is you save the image after multiplying it by 255. This will convert its datatype from bool to int32. Now the scipy.mics.imsave can save the image properly.
> 
> Just try changing the line scipy.misc.imsave('../enhanced/' + img_name,enhanced_img); to scipy.misc.imsave('../enhanced/' + img_name, 255*enhanced_img);

thankuu it worked

**Comment by wahyubram82** [comment] 2019-06-02 19:05
I think the problem is in deprecated module....
i use an updated module...
![image](https://user-images.githubusercontent.com/44884345/58765756-6eb30b80-85a0-11e9-8785-abdde5d61702.png)

the result still totaly blank

i try process step by step to view the result, the problem is came from scipy module that unable read the file, it's totally white. I'm using scipy 1.1.0. 

that's mean the problem come from the reading module.

so i will re-modified the module.
need your assistance to do this...

first, i want to use the opencv module...to read the image file.
what should i do to make it working with your script.
the first attempt is i read the file and turn it to grey colour.
```
import cv2
img = cv2.imread(sys.argv[1])
img = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
```

may i ask, what the purpose of this line in main_enhancement.py:

```
[if(len(img.shape)>2):
    img = np.dot(img[...,:3], [0.299, 0.587, 0.114])
```

is this mean change into grey colour?
because i see this comment script
`#img = cv2.cvtColor(src,cv2.COLOR_BGR2GRAY)`

please help me to make it work with opencv module
my opencv module version is 4.1.0, build with CUDA, CUDNN and non-free module

**Comment by wahyubram82** [comment] 2019-06-03 06:05
i try to rebuild the script because of  the deprecated  function in scipy module
it's caused failure in the first step, reading image resulting all white picture

so, i do it step by step for all your method, and still got all black result.
the image target still:
https://www.futurity.org/wp/wp-content/uploads/2017/04/fingerprint_1600.jpg

![image](https://user-images.githubusercontent.com/44884345/58778852-4c4fdb00-85fe-11e9-8126-d9330cedd15e.png)



i put all step in one file, test it one by one. the problem is i don't know which step should change the image, and what kind of change should be.

here the scipt:

```
import cv2
import numpy as np
import sys
from scipy import signal, ndimage
import math

datafp = 'C:/Users/admin/Pictures/fingerprint/database/5.jpg' #change this picture path
img = cv2.imread(datafp)
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

#ridge segment part
def normalise(img,mean,std):
    normed = (img - np.mean(img))/(np.std(img));    
    return(normed)

im = normalise(gray, 0, 1)
rows, cols = gray.shape
blksze = 16
thresh = 0.01
new_rows =  np.int(blksze * np.ceil((np.float(rows))/(np.float(blksze))))
new_cols =  np.int(blksze * np.ceil((np.float(cols))/(np.float(blksze))))
    
padded_img = np.zeros((new_rows,new_cols));
stddevim = np.zeros((new_rows,new_cols));
    
padded_img[0:rows][:,0:cols] = im;
    
for i in range(0,new_rows,blksze):
	for j in range(0,new_cols,blksze):
		block = padded_img[i:i+blksze][:,j:j+blksze]
		stddevim[i:i+blksze][:,j:j+blksze] = np.std(block)*np.ones(block.shape)
    
stddevim = stddevim[0:rows][:,0:cols]
mask = stddevim > thresh;
mean_val = np.mean(im[mask]);
std_val = np.std(im[mask]);
normim = (im - mean_val)/(std_val)
```

ok, until here i test the result of normim, still works fine.
i use this script to see the result
```
cv2.imshow('cek', normim)
cv2.waitKey(1)

```
and the screen shot of the result
![image](https://user-images.githubusercontent.com/44884345/58778755-f54a0600-85fd-11e9-9578-16a756ea1cb5.png)

then continue scripting...
`cv2.destroyAllWindows()`

```
#ridge orient
gradientsigma = 1;
blocksigma = 7;
orientsmoothsigma = 7
sze = np.fix(6*gradientsigma)
if np.remainder(sze,2) == 0:
	sze = sze+1;
        
gauss = cv2.getGaussianKernel(np.int(sze),gradientsigma);
f = gauss * gauss.T;

fy,fx = np.gradient(f);     #Gradient of Gaussian
Gx = signal.convolve2d(normim,fx,mode='same');    
Gy = signal.convolve2d(normim,fy,mode='same');
Gxx = np.power(Gx,2);
Gyy = np.power(Gy,2);
Gxy = Gx*Gy;
    
#Now smooth the covariance data to perform a weighted summation of the data.    

sze = np.fix(6*blocksigma);
gauss = cv2.getGaussianKernel(np.int(sze),blocksigma);
f = gauss * gauss.T;

Gxx = ndimage.convolve(Gxx,f);
Gyy = ndimage.convolve(Gyy,f);
Gxy = 2*ndimage.convolve(Gxy,f);

# Analytic solution of principal direction
denom = np.sqrt(np.power(Gxy,2) + np.power((Gxx - Gyy),2)) + np.finfo(float).eps;
sin2theta = Gxy/denom;            # Sine and cosine of doubled angles
cos2theta = (Gxx-Gyy)/denom;
sze = np.fix(6*orientsmoothsigma)

if np.remainder(sze,2) == 0:
	sze = sze+1;    
gauss = cv2.getGaussianKernel(np.int(sze),orientsmoothsigma);
f = gauss * gauss.T;
cos2theta = ndimage.convolve(cos2theta,f); # Smoothed sine and cosine of
sin2theta = ndimage.convolve(sin2theta,f); # doubled angles

orientim = np.pi/2 + np.arctan2(sin2theta,cos2theta)/2

```
until here, still not sure, it's works or not. but i try to see the result with the sameway 
```
cv2.imshow('test', orientim)
cv2.waitKey(1)
```
the result is like this, and really not sure this is right or not.
![image](https://user-images.githubusercontent.com/44884345/58779191-54f4e100-85ff-11e9-8b47-9f75c73e187b.png)

ok, continue scripting...but until here, i don't know anymore, which part is an image that can be check like above...

`cv2.destroyAllWindows()`

```
#frequency ridges
blksze = 38
windsze = 5
minWaveLength = 5
maxWaveLength = 15
freq = np.zeros((rows,cols))

for r in range(0,rows-blksze,blksze):
	for c in range(0,cols-blksze,blksze):
		blkim = normim[r:r+blksze][:,c:c+blksze]
		blkor = orientim[r:r+blksze][:,c:c+blksze]
		#rows,cols = np.shape(blkim)
		cosorient = np.mean(np.cos(2*blkor))
		sinorient = np.mean(np.sin(2*blkor))
		orient = math.atan2(sinorient,cosorient)/2
		rotim = scipy.ndimage.rotate(blkim,orient/np.pi*180 + 90,axes=(1,0),reshape = False,order = 3,mode = 'nearest')
		proj = np.sum(rotim,axis = 0)
		dilation = scipy.ndimage.grey_dilation(proj, windsze,structure=np.ones(windsze))
		temp = np.abs(dilation - proj)
		peak_thresh = 2;    
		maxpts = (temp<peak_thresh) & (proj > np.mean(proj));
		maxind = np.where(maxpts)
		rows_maxind,cols_maxind = np.shape(maxind)
		if(cols_maxind<2):
			freqim = np.zeros(blkim.shape)
		else:
			NoOfPeaks = cols_maxind
			waveLength = (maxind[0][cols_maxind-1] - maxind[0][0])/(NoOfPeaks - 1)
			if waveLength>=minWaveLength and waveLength<=maxWaveLength:
				freqim = 1/np.double(waveLength) * np.ones(blkim.shape)
			else:
				freqim = np.zeros(blkim.shape)
		freq[r:r+blksze][:,c:c+blksze] = freqim

freq = freq*mask
rows, cols = gray.shape
freq_1d = np.reshape(freq,(1,rows*cols))
ind = np.where(freq_1d>0)
ind = np.array(ind);
ind = ind[1,:]
non_zero_elems_in_freq = freq_1d[0][ind]
meanfreq = np.mean(non_zero_elems_in_freq)
medianfreq = np.median(non_zero_elems_in_freq)

#ridge filter

freq = meanfreq*mask
kx = 0.65;ky = 0.65
angleInc = 3
im = np.double(normim)
rows,cols = im.shape
newim = np.zeros((rows,cols))
freq_1d = np.reshape(freq,(1,rows*cols))
ind = np.where(freq_1d>0)
ind = np.array(ind);
ind = ind[1,:]
non_zero_elems_in_freq = freq_1d[0][ind]; 
non_zero_elems_in_freq = np.double(np.round((non_zero_elems_in_freq*100)))/100
unfreq = np.unique(non_zero_elems_in_freq)
sigmax = 1/unfreq[0]*kx;
sigmay = 1/unfreq[0]*ky;

sze = np.round(3*np.max([sigmax,sigmay]));

x,y = np.meshgrid(np.linspace(-sze,sze,(2*sze + 1)),np.linspace(-sze,sze,(2*sze + 1)));

reffilter = np.exp(-(( (np.power(x,2))/(sigmax*sigmax) + (np.power(y,2))/(sigmay*sigmay)))) * np.cos(2*np.pi*unfreq[0]*x); # this is the original gabor filter

filt_rows, filt_cols = reffilter.shape;    

gabor_filter = np.array(np.zeros((int(180/angleInc), (filt_rows), (filt_cols)), dtype = int));
angle_for_iter = (0,180/angleInc)
start_angle, last_angle = angle_for_iter
start_angle = int(start_angle)
last_angle = int(last_angle)
for o in range(start_angle, last_angle):
	rot_filt = scipy.ndimage.rotate(reffilter,-(o*angleInc + 90),reshape = False)
	gabor_filter[o] = rot_filt
	
maxsze = int(sze);   
temp = freq>0;    
validr,validc = np.where(temp)    
temp1 = validr>maxsze;
temp2 = validr<rows - maxsze;
temp3 = validc>maxsze;
temp4 = validc<cols - maxsze;
final_temp = temp1 & temp2 & temp3 & temp4;
finalind = np.where(final_temp)
maxorientindex = np.round(180/angleInc);
orientindex = np.round(orientim/np.pi*180/angleInc)
for i in range(0,rows):
	for j in range(0,cols):
		if(orientindex[i][j] < 1):
			orientindex[i][j] = orientindex[i][j] + maxorientindex
		if(orientindex[i][j] > maxorientindex):
			orientindex[i][j] = orientindex[i][j] - maxorientindex
finalind_rows,finalind_cols = np.shape(finalind)
sze = int(sze)
for k in range(0,finalind_cols):
	r = validr[finalind[0][k]]
	c = validc[finalind[0][k]]
	img_block = im[r-sze:r+sze + 1][:,c-sze:c+sze + 1]
	newim[r][c] = np.sum(img_block * gabor_filter[int(orientindex[r][c]) - 1])
enhanced_img = (newim < -3)

```

then the last result is:
![image](https://user-images.githubusercontent.com/44884345/58779410-0eec4d00-8600-11e9-9abb-424b963d6d7f.png)

**Comment by Utkarsh-Deshmukh** [comment] 2019-06-03 20:23
- could you see how the newim looks like (This is just before the thresholding)
- Could you check if this works:   cv2.imshow('test', 255 * (enhanced_img));     cv2.waitKey(1)

If the second option works, you could save the image using:
scipy.misc.imsave('../enhanced/' + img_name, 255 * (enhanced_img))

The problem could be that the image is being displayed as a uint8 image, but the content is binary.
Hence, the pixel value of 1 is not visible. By multiplying it by 255, if there is any binary content, it will be magnified.

**Comment by wahyubram82** [comment] 2019-06-05 08:58
sorry for not detail, the last result is from the newim that show in my previous post. i capture it after do:
```
cv2.imshow('test', 255 * (enhanced_img))
cv2.waitKey(1)
```

dear Mr. Utkarsh, i try my best to not asking first, but try best what can i do.
that's why i explain many explanation, and caused me not explaining something else, sorry.

Ithink, the problem that I found not how to save the file,
I already try:
`scipy.misc.imsave('../enhanced/' + img_name, 255 * (enhanced_img))`
because, this is the frist clue that you give to @Kkaranmore .
so pleased, it's not works.

so i try rebuild, with opencv.
i found that your method not working if I only do:
```
cv2.imshow('test', (enhanced_img))
cv2.waitKey(1)
```
it's error.
it's not error if i multiplying with 255
```
cv2.imshow('test', 255 * (enhanced_img))
cv2.waitKey(1)
```

so I debuging it....
normalized step is work great...
when i step to another step, the orintim showing a 'strange' result.
do you think it's normal the orientim?
i think, the problem come start from the orientim result.

**Comment by Utkarsh-Deshmukh** [comment] 2019-06-07 23:38
I think your orienim looks fine. Remember, it is the orientation map which will only display what the direction of the ridges will be.

**Comment by Utkarsh-Deshmukh** [comment] 2019-06-07 23:39
has the algorithm worked for any image at all? or is it failing everytime?
The issue is weird because, I can recreate it on my end.

Best Regards

**Comment by wahyubram82** [comment] 2019-06-09 23:27
the failed result happened for every image.

but
i have a great progress....

i try to cek all script, and found that 'newim', the variable from the script, before the script: 
`enhanced_img = (newim < -3)`

the last script, that resulting newim
```
for k in range(0,finalind_cols):
	r = validr[finalind[0][k]]
	c = validc[finalind[0][k]]
	img_block = im[r-sze:r+sze + 1][:,c-sze:c+sze + 1]
	newim[r][c] = np.sum(img_block * gabor_filter[int(orientindex[r][c]) - 1])
```

looks like this:
![image](https://user-images.githubusercontent.com/44884345/59165539-a3e2cf00-8b47-11e9-9256-5d8345e06b4d.png)


the script, `enhanced_img = (newim < -3)`, make it totally black.
so we only need to discuss, why `enhanced_img = (newim < -3)` needed.
what the purpose to make this script, i mean, maybe i can found the problem.

newim form is matrice array, did you want to change the value of newim?
if i want to change the value, it should be like this:

rows, cols = newim.shape
```
for i in range(0,rows):
    for j in range(0, cols):
        if newim[i,j] < -3: #conditional script base on need
            newim[i,j] = 'CHANGE THE VALUE HERE'
        else:
            pass
```

**Comment by Utkarsh-Deshmukh** [comment] 2019-06-18 01:22
Hi,
Here are the outputs that I get at every stage in the pipeline:

![image](https://user-images.githubusercontent.com/13918778/59646609-8ce64300-912c-11e9-8dee-e192fd41f842.png)


You can tally the output at every stage in the pipeline to understand the problem.
* I have also given snippets to understand how I generated every output in the pipeline.

**Comment by wahyubram82** [comment] 2019-06-28 18:17
ok...thanks a lot for your explanation.....I almost give up til read your answer

**Comment by rishav1802** [comment] 2019-07-18 11:35
hi utkarsh,
i can't understand what the significance of using -3 is
after using newim<-3 i get a completely black image

**Comment by Utkarsh-Deshmukh** [comment] 2019-07-18 20:03
> hi utkarsh,
> i can't understand what the significance of using -3 is
> after using newim<-3 i get a completely black image

This final step is a simple thresholding function. you could try changing the threshold value to see if you get good results. You could also try fancy stuff like adaptive threshold using a local metric.

**Comment by rishav1802** [comment] 2019-07-19 09:52
there isn't clarity in my outputs ..as compared to ur newim, my newim isn't as smoothly colored,i.e. at the boundary white outlines gets created

**Comment by rishav1802** [comment] 2019-07-19 11:04
> > thanks for your reponses....but it keep give me picture which it, totally black.
> > please try your script to this picture:
> > https://www.futurity.org/wp/wp-content/uploads/2017/04/fingerprint_1600.jpg
> 
> It is funny because i am getting the enhanced image out. Here is my output:
> ![image](https://user-images.githubusercontent.com/13918778/56233149-4b0b2480-6037-11e9-8bd6-36c1e01f88e6.png)

pls tell me how do i get enhanced image like this

**Comment by Utkarsh-Deshmukh** [comment] 2019-07-22 18:14
The output image that you have sent seems fine. you co do some post thresholding cleanup like morphological closing to get rid on spurious holes.

- You may also experiment by changing the **blocksigma** parameter in the image_enhance.py script
This will control the smoothing effect while computing the ridge orientations.
- You may also want to experiment with the blksze parameter in image_enhance.py script.
This will control the size of the blocks that are used in the frequency estimation of the ridges

I experimented with a blksze value of 38 and blocksigma=9.

**Closed** 2019-10-09 18:13 UTC
